"""Shared pytest fixtures for meta_one."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest


@pytest.fixture
def tmp_node_project(tmp_path: Path) -> Path:
    """Node.js project with package.json, lockfile, .env files, Makefile, and TS files.

    Args:
        tmp_path (Path): Pytest temporary path.

    Returns:
        Path: Path to the mocked project.
    """
    (tmp_path / "package.json").write_text(
        json.dumps(
            {
                "name": "my-node-app",
                "version": "1.0.0",
                "scripts": {
                    "dev": "next dev",
                    "build": "next build",
                    "test": "jest",
                    "lint": "eslint .",
                },
                "dependencies": {
                    "react": "^18.0.0",
                    "next": "^13.0.0",
                    "axios": "^1.0.0",
                },
                "devDependencies": {"typescript": "^5.0.0", "eslint": "^8.0.0"},
            }
        )
    )

    (tmp_path / "package-lock.json").write_text(
        json.dumps(
            {
                "name": "my-node-app",
                "version": "1.0.0",
                "lockfileVersion": 3,
                "packages": {},
            }
        )
    )

    (tmp_path / ".env.example").write_text(
        "DATABASE_URL=\nNEXTAUTH_SECRET=\nNEXT_PUBLIC_URL=http://localhost:3000\nDEBUG=\n"
    )

    (tmp_path / ".env").write_text(
        "DATABASE_URL=postgres://...\nNEXTAUTH_SECRET=secret123\nNEXT_PUBLIC_URL=http://localhost:3000\n"
    )

    (tmp_path / "Makefile").write_text(
        "dev:\n\tnpm run dev\nbuild:\n\tnpm run build\ntest:\n\tnpm run test\n"
    )

    (tmp_path / "tsconfig.json").write_text(
        json.dumps({"compilerOptions": {"strict": True}})
    )

    src = tmp_path / "src"
    src.mkdir()
    (src / "index.ts").write_text("console.log(process.env.DATABASE_URL);")
    lib = src / "lib"
    lib.mkdir()
    (lib / "auth.ts").write_text("console.log(process.env.NEXTAUTH_SECRET);")

    # Git repo
    subprocess.run(["git", "init"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "add", "."], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=Alice",
            "-c",
            "user.email=alice@example.com",
            "commit",
            "-m",
            "init",
        ],
        cwd=tmp_path,
        check=True,
        capture_output=True,
    )

    (tmp_path / "README.md").write_text("Hello")
    subprocess.run(
        ["git", "add", "README.md"], cwd=tmp_path, check=True, capture_output=True
    )
    subprocess.run(
        [
            "git",
            "-c",
            "user.name=Bob",
            "-c",
            "user.email=bob@example.com",
            "commit",
            "-m",
            "add readme",
        ],
        cwd=tmp_path,
        check=True,
        capture_output=True,
    )

    return tmp_path


@pytest.fixture
def tmp_python_project(tmp_path: Path) -> Path:
    """Python project with pyproject.toml, uv.lock, and sample .py files.

    Args:
        tmp_path (Path): Pytest temporary path.

    Returns:
        Path: Path to the mocked project.
    """
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "my-py-app"\nversion = "0.1.0"\ndependencies = ["fastapi", "uvicorn"]\n\n[dependency-groups]\ndev = ["pytest", "ruff"]\n'
    )

    (tmp_path / "uv.lock").write_text("version = 1\n")

    (tmp_path / ".env.example").write_text("SECRET_KEY=\n")

    src = tmp_path / "src"
    src.mkdir()
    (src / "app.py").write_text('import os\nprint(os.environ["SECRET_KEY"])')

    subprocess.run(["git", "init"], cwd=tmp_path, check=True, capture_output=True)

    return tmp_path


@pytest.fixture
def tmp_rust_project(tmp_path: Path) -> Path:
    """Rust project with Cargo.toml, Cargo.lock, and sample .rs files.

    Args:
        tmp_path (Path): Pytest temporary path.

    Returns:
        Path: Path to the mocked project.
    """
    (tmp_path / "Cargo.toml").write_text(
        '[package]\nname = "my-rs-app"\nversion = "0.1.0"\n'
    )
    (tmp_path / "Cargo.lock").write_text(
        "# This file is automatically @generated by Cargo.\n"
    )

    src = tmp_path / "src"
    src.mkdir()
    (src / "main.rs").write_text("fn main() {}")

    return tmp_path


@pytest.fixture
def tmp_empty_project(tmp_path: Path) -> Path:
    """Empty directory with no marker files.

    Args:
        tmp_path (Path): Pytest temporary path.

    Returns:
        Path: Path to the empty directory.
    """
    return tmp_path
